# This file was generated by GoReleaser. DO NOT EDIT.
cask "kairo" do
  version "1.1.7"

  on_macos do
    on_intel do
      sha256 "4ca9ba92d9eacba8b857f88ff6d98b361016bc16d05b0e641b7fa9d515a8ca4e"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4d5925aaa322b17725272c8962640148f010bb85a73959231831d70ee3f9343c"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b267ea8aed140f8a145954b0a8bbcb1573a5286e910e766f89b041a87df900f0"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "124c101ba9a50ddd2962f415e15f681e967ecfc5e55f653d511867890abc9bd6"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_linux_arm64.tar.gz"
    end
  end

  name "kairo"
  desc "Minimal, powerful task management"
  homepage "https://github.com/programmersd21/kairo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kairo"

  # No zap stanza required

end
