# This file was generated by GoReleaser. DO NOT EDIT.
cask "kairo" do
  version "1.1.7"

  on_macos do
    on_intel do
      sha256 "5063777064fa6a1693c00b884c39e26a052495573d4f2990a43e44d7303b4926"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "88ec3dbfa56d5be9f94cc8404e5b5d7c610c38f0c2492379770f25255505261e"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "514f8f35f82dabdc506438139f0bc38ed77d99ffbb862d5cb887b20d8df2ae69"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fb7874b6d964926a6c8eab0795a3f92aa84004e33310d0d114c9f8e4f4b00551"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_linux_arm64.tar.gz"
    end
  end

  name "kairo"
  desc "Minimal, powerful task management"
  homepage "https://github.com/programmersd21/kairo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kairo"

  # No zap stanza required

end
