# This file was generated by GoReleaser. DO NOT EDIT.
cask "kairo" do
  version "1.1.9"

  on_macos do
    on_intel do
      sha256 "2e260c837078c23222d5cc203ac83c782a21cecffed6c9fd6fad99feffb77efe"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "217731af3c09319bc9b3d51e0ddb069cb9ecdb6721a0ec01c636f42fb95870f9"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9e7d4ca6b91931623b8bc39389e49a09920b1fd373d36972af66efe290a7bd56"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2cb9f42dea690d697769b1cd23c81a32dd544526e0d6aaed32e16f3a092bd1a3"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_linux_arm64.tar.gz"
    end
  end

  name "kairo"
  desc "Minimal, powerful task management"
  homepage "https://github.com/programmersd21/kairo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kairo"

  # No zap stanza required

end
