# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: kairo

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: kairo
    main: ./cmd/kairo
    binary: kairo

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    flags:
      - -trimpath

    mod_timestamp: "{{ .CommitTimestamp }}"

    ldflags:
      - -s -w
      - -X github.com/programmersd21/kairo/internal/buildinfo.Version={{ .Version }}
      - -X github.com/programmersd21/kairo/internal/buildinfo.Commit={{ .ShortCommit }}
      - -X github.com/programmersd21/kairo/internal/buildinfo.Date={{ .CommitDate }}

archives:
  - id: kairo
    ids:
      - kairo

    formats:
      - tar.gz

    format_overrides:
      - goos: windows
        formats:
          - zip

    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}

    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - configs/*.toml

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-devel"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^README'
      - '^Merge'
      - '^Brew'

release:
  draft: false
  prerelease: auto

brews:
  - name: kairo

    ids:
      - kairo

    repository:
      owner: programmersd21
      name: homebrew-kairo
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

    directory: Formula

    homepage: "https://github.com/programmersd21/kairo"
    description: "Minimal, powerful task management"
    license: "MIT"

    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    commit_msg_template: "brew: update {{ .ProjectName }} to {{ .Tag }}"

    install: |
      bin.install "kairo"

    test: |
      system "#{bin}/kairo", "--version"

    skip_upload: auto
    