# This file was generated by GoReleaser. DO NOT EDIT.
cask "kairo" do
  version "1.2.2"

  on_macos do
    on_intel do
      sha256 "aca5674268627a4b2b6162e740629daf9025327106e69729989886edfd705d51"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2dc42f19dd3a6fa6456486afbfbb4910db5cb7154b3339c760f4fdf3b3074b0b"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc7883cdde5fbba094547e3682235b34e8e0fce4152ea18bd4430aa8a4a133b1"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9043141e30c8238c69a4a97a520dc6ec993dd62ea8de9df6130fb3697fc385c1"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_linux_arm64.tar.gz"
    end
  end

  name "kairo"
  desc "Minimal, powerful task management"
  homepage "https://github.com/programmersd21/kairo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kairo"

  # No zap stanza required

end
