# This file was generated by GoReleaser. DO NOT EDIT.
cask "kairo" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "fc51159bfb05adb3c8aaaab6c2910585aaea39416848e9fa5d00c8b5d9e93a8b"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "93893dae2f2cdf02665d4532fb2375de432a87c017abaa7ca6d1d99521313a37"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ad562c7a3cc8724df5d5ce50260d4a0824e86e1d593bc79b5e83045fa68ee04a"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "945910d1c15dbbd8ae8745aa0e112d36dfe6eec38aa1ae30b9105503f93d7f35"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_linux_arm64.tar.gz"
    end
  end

  name "kairo"
  desc "Minimal, powerful task management"
  homepage "https://github.com/programmersd21/kairo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kairo"

  # No zap stanza required

end
