# This file was generated by GoReleaser. DO NOT EDIT.
cask "kairo" do
  version "1.2.1"

  on_macos do
    on_intel do
      sha256 "f94642758bf1d8902020326ed5f7da8b559c5287050320f5116a0d9c35c1911c"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b4cf3ade0ebc18f1065fc43af4945ec1d88cb73924d7334da54ae0bd4c1a9060"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b152120bd3b6b8e77f1d46b8ab9ee929dc8f201d9ac82f151fb0024cc611d8c7"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8bc84d88c8af754afd3e6d91b07a6088963f0cae7e8f4bfde0a35bb3058b3027"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_linux_arm64.tar.gz"
    end
  end

  name "kairo"
  desc "Minimal, powerful task management"
  homepage "https://github.com/programmersd21/kairo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kairo"

  # No zap stanza required

end
